### PR TITLE
Fixed notify_change issue.(clipboard chain broken)

### PR DESCRIPTION
**Pull request by u338steven**
# steps
#### 1.Run this code.

test1.rb

``` ruby
require 'win32/clipboard'

Win32::Clipboard.notify_change{puts "foo"}
```
#### 2. Run this code.

test2.rb:

``` ruby
require 'win32/clipboard'

Win32::Clipboard.notify_change{puts "bar"}
```
#### 3. Kill a process of "ruby test2.rb" and then copy something.
# problem

The result should be "foo", but nothing.

I'm using the following:

Windows 7 (x64)
Ruby 2.0.0p353 (2013-11-22)[x64-mingw32]
win32/clipboard 0.6.2

### CODE REVIEW

**Comment by djberg96** [comment]
Very nice, thank you!

**Comment by u338steven** [comment]
I guess failure of JRuby could be caused by rubygems.
If rubygems version is 2.1.X, please upgrade it.

I ran the chain tests on version from 2.1.9 to 2.2.2.
Results:
rubygems version: results
2.1.9-11: failure
2.2.0-2: success

**Comment by djberg96** [comment]
Ok, I tried running with rubygems 2.2.2, and it gave me a LoadError and hung:

```
C:\jruby -v
jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) Client VM 1.7.0_45-b18 [Windows 7-x86]

C:\>jruby -S gem -v
io/console not supported; tty will not be manipulated
2.2.2

C:\>jruby -S rake test:chain
...
LoadError: no such file to load -- win32/clipboard
require at org/jruby/RubyKernel.java:1083
require at C:/jruby-1.7.10/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
(root) at C:/Users/djberge/Repositories/win32-clipboard/test/notify.rb:1 undefined method `chomp' for nil:NilClass
```

**Comment by u338steven** [comment]
> Wouldn't the callback, and thus the call to ChangeClipboardChain, happen before SetClipboardViewer had been called?
> Does the handle need to be added first?

You're right.
I fixed it and JRuby hangs(issue #9)

But I cannot confirm LoadError...
Hmm...please show me your gem list.

```
C:\>jruby -v
jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_51-b13 [Windows 7-amd64]

C:\>jruby -S gem -v
io/console not supported; tty will not be manipulated
2.2.2

C:\>jruby -S rake test:chain
...
Loaded suite c:/ruby/jruby-1.7.10/lib/ruby/shared/rake/rake_test_loader
Started
io/console not supported; tty will not be manipulated
Added clipboard viewer 1
io/console not supported; tty will not be manipulated
Added clipboard viewer 2
io/console not supported; tty will not be manipulated
Added clipboard viewer 3
.

Finished in 12.499 seconds.

1 tests, 9 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifica
tions
100% passed

0.08 tests/s, 0.72 assertions/s
```

my gem list

```
C:\>jruby -S gem list
io/console not supported; tty will not be manipulated

*** LOCAL GEMS ***

bouncy-castle-java (1.5.0147)
ffi (1.9.3 java)
jruby-openssl (0.9.3)
jruby-win32ole (0.8.5)
json (1.8.0 java)
krypt (0.0.1)
krypt-core (0.0.1 universal-java)
krypt-provider-jdk (0.0.1)
minitest (5.2.2)
rake (10.1.0)
rdoc (4.0.1)
test-unit (2.5.5)
win32-clipboard (0.6.2)
```

**Comment by djberg96** [comment]
Ah, I see it's working because you installed win32-clipboard as a gem first. Once I did that it worked. This is some sort of strange rake or gem issue with JRuby, so I won't worry about it.

Oddly I still get a timeout error with MRI, but it works fine with JRuby now.

**Comment by u338steven** [comment]
That makes sense!
Thank you for the information!

On MRI, I installed win32-clipboard as a gem first too.

In test:chain, child processes run.
The child processes read old version of win32-clipboard.
So it causes timeout error.

I'll fix test:chain for reading new version.

**Pull request merged**
